# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8a6f13603c047ab7fec315b7a44b47220e10092342f9bb56a70ea0a598a725e72d8c2c813b551a92d8d8f77bbd9179afd961432e45fda6d0560002e4b61ebf7

test:
  secret_key_base: 8d6ffc2f31110fbff02ae2c8e26f0166ddf45047f6407ba1095e48aa4c2a33ffdf7c591482718b1ca30fe68ff312bf840215ecb6253bf49a90ef000934d94f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
